INSERT INTO CITY (CONTINENT, COUNTRY, STATE, CITY, POPULATION, AREA) VALUES 
    ('North America', 'United States', 'California', 'Los Angeles', 3979576, 1302);

INSERT INTO CITY (CONTINENT, COUNTRY, STATE, CITY, POPULATION, AREA) VALUES 
    ('Europe', 'Germany', 'Bavaria', 'Munich', 1471508, 310.7);

INSERT INTO CITY (CONTINENT, COUNTRY, STATE, CITY, POPULATION, AREA) VALUES 
    ('Asia', 'Japan', 'Tokyo', 'Tokyo', 13929286, 2191);

INSERT INTO CITY (CONTINENT, COUNTRY, STATE, CITY, POPULATION, AREA) VALUES 
    ('South America', 'Brazil', 'São Paulo', 'São Paulo', 12325232, 1521);

INSERT INTO CITY (CONTINENT, COUNTRY, STATE, CITY, POPULATION, AREA) VALUES 
    ('Africa', 'Nigeria', 'Lagos', 'Lagos', 14160000, 1171);